baseurl = "http://tharman4pm.com/"
languageCode = "en-SG"
title = "Tharman for PM"
theme = "casper"

[permalinks]
  post = "/:year/:month/:slug/"

[params]
  description = "Tharman for Prime Minister"
  cover = "images/sg-flag-1280.png"
  author = "tharman4pm"
  twitterName = "tharman4pm"
  authorlocation = "Singapore, Singapore"
  googleAnalyticsUserID = "UA-37884921-6"
  hideHUGOSupport = false
